In [4]:
#실습1
data1 = ('A','B')
data2 = ('C',)
data3 = data1 + data2

In [26]:
#실습2
import numpy as np

n = int(input("정수를 입력하세요: "))
A = np.zeros((n,n))
for j in range(n):
    for i in range(n):
        A[j,i] = j*n+i+1
print(A)

정수를 입력하세요:  6


[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36.]]


In [25]:
#실습3
#실습 1에서 수행한 결과를 reshape을 이용해서 1차원 형태로 변환한다.

print(A.reshape(-1,))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.]


In [ ]:
#실습4
# 1. 임의의 이미지 파일을 불러온다.
# 2. Numpy의 expend_dims를 사용해서 이미지 파일의 차원을 하나 더 늘려 
#(H,W,C)을 (B,H,W,C)로 확장한다.
# (이미지 출력 불필요)
# 3. Numpy의 transpoed를 이용해서 차원의 순서를 (B,W,H,C)에서 (B,C,W,H)로 변경한다.
# (이미지 출력 불필요)
# imge.shape를 통해 결과 확인

In [27]:
#My Code
import numpy as np
from PIL import Image

image = Image.open('input.jpg')
image_np = np.array(image)

image_expanded = np.expand_dims(image_np, axis=0)

image_transposed = np.transpose(image_expanded, (0, 3, 2, 1))

print("Original shape:", image_np.shape)
print("Expanded shape:", image_expanded.shape)
print("Transposed shape:", image_transposed.shape)

Original shape: (757, 560, 3)
Expanded shape: (1, 757, 560, 3)
Transposed shape: (1, 3, 560, 757)


In [ ]:
#강사님 Code

In [31]:
import cv2
img = cv2.imread('./input.jpg')
print(img.shape)
img_expend = np.expand_dims(img,0)
print(img_expend.shape)
img_expend_T = img_expend.transpose((0,3,1,2))
print(img_expend_T.shape)

(757, 560, 3)
(1, 757, 560, 3)
(1, 3, 757, 560)


In [38]:
#실습5
import cv2
import numpy as np

img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel) #여기를 직접 구현
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


In [1]:
import cv2 
import numpy as np

img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
print(kernel)


padded_img = np.pad(img, ((1, 1), (1, 1)), mode='constant')

output = np.zeros_like(img)

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        sum = 0
        for a in range(kernel.shape[0]):
            for b in range(kernel.shape[1]):
                sum += padded_img[i+a, j+b] * kernel[a, b]
        output[i, j] = np.clip(sum, 0, 255)

cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]
