In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2
import numpy as np

# Identity
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, 0, 0],[0, 1, 0], [0, 0, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[0 0 0]
 [0 1 0]
 [0 0 0]]


Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation


In [2]:
import cv2
import numpy as np

# Ridge detection
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0],[-1, 4, -1], [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]


Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation


In [4]:
import cv2
import numpy as np

# edge detection
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


In [ ]:
import cv2
import numpy as np

# shaprp
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0],[-1, 5, -1], [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]


In [ ]:
import cv2
import numpy as np

# Box blur
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/9, 1/9, 1/9],
                   [1/9, 1/9, 1/9], 
                   [1/9, 1/9, 1/9]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

# Gaussian blur 3x3
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/16, 2/16, 1/16],
                   [2/16, 4/16, 2/16], 
                   [1/16, 2/16, 1/16]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

# Gausian blur 5x5
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/256,  4/256,   6/256 ,  4/256, 1/256],
                   [4/256, 16/256, 246/256 , 16/256, 4/256], 
                   [6/256, 24/256,  36/256 , 24/256, 6/256],
                   [4/256, 16/256,  24/256 , 16/256, 4/256],
                   [1/256,  4/256,   6/256 ,  4/256, 1/256]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

cv2.destroyAllWindows()