In [10]:
import numpy as np

In [11]:
# 주어진 데이터
data1 = ('A', 'B')
data2 = ('C',)

# data1과 data2를 결합
data3 = data1 + data2

# data1을 리스트로 변환하고 'C'를 추가한 후 다시 튜플로 변환 (실습 1)
data1_list = list(data1)
data1_list.append('C')
data1_list = tuple(data1_list)

In [13]:
n = 6
A = np.zeros((n,n))
for j in range(n) : 
    for i in range(n):
        A[j,i] = j*n+i
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [17]:
print(A.reshape(-1))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.]
