### 실습 2) 정수 n을 입력받아 nxn 크기의 숫자 사각형을 출력

In [4]:
import numpy as np

In [5]:
def print_number_square(n):
    # 초기 숫자 설정
    number = 1
    
    # n x n 크기의 숫자 사각형 생성 및 출력
    for i in range(n):
        for j in range(n):
            print(number, end=' ')
            number += 1
        print()

# 사용자로부터 정수 n 입력받기
n = int(input("정수 n을 입력하세요: "))

# 숫자 사각형 출력
print_number_square(n)


정수 n을 입력하세요:  4


1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 


In [8]:
n = 6
A = np.zeros((n,n))
for j in range(n) : 
    for i in range(n):
        A[j,i] = j*n+i
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
