In [1]:
import cv2
import numpy as np

# 이미지 읽기 (grayscale)
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)

# 커널 정의
kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
print("Kernel:\n", kernel)

# 이미지의 높이와 너비
image_height, image_width = img.shape

# 커널의 높이와 너비
kernel_height, kernel_width = kernel.shape

# 패딩 크기 계산
pad_height = kernel_height // 2
pad_width = kernel_width // 2

# 입력 이미지 패딩 추가
padded_img = np.pad(img, ((pad_height, pad_height), (pad_width, pad_width)), mode='constant')

# 출력 이미지 초기화
output = np.zeros_like(img)

# 컨볼루션 연산 수행
for i in range(image_height):
    for j in range(image_width):
        # 현재 패치 추출
        region = padded_img[i:i + kernel_height, j:j + kernel_width]
        # 커널과 패치의 element-wise 곱셈 및 합산
        output[i, j] = np.sum(region * kernel)

# 결과 출력
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

Kernel:
 [[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation


In [4]:
import cv2
import copy
import numpy as np
import matplotlib.pyplot as plt

# 이미지 불러오가
img = cv2.imread('input.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
kernel = np.array([[1,1,1], [1, -8, 1], [1, 1, 1]])
imgcpy = copy.deepcopy(img)
imgcpy2 = copy.deepcopy(img)
imgcpy2 = np.zeros( (imgcpy.shape[0], imgcpy.shape[1], imgcpy.shape[2]))

for h in range(2, img.shape[0] -1):
    for w in range(2, img.shape[1]-1):
        for c in range(2, img.shape[2]):
            img_tmp = np.dot(
                img[h-1:h-1+kernel.shape[0], w-1:w-1+kernel.shape[1], c],
                kernel)
            imgcpy2[h,w,c] = np.sum(img_tmp)

cv2.imshow("Edge", imgcpy2/255)
cv2.waitKey(1)



-1