In [1]:
# 실습1 

data1 = ('A','B')
data2 = ('C',)
data3 = data1 + data2
print(data3)
print(type(data3))

('A', 'B', 'C')
<class 'tuple'>


In [2]:
# list로 바꿨다가 tuple로

data1 = ('A','B')
data1_list = list(data1)
data1_list.append('C')
data1_list = tuple(data1_list)
print(data1_list)
print(type(data1_list))

('A', 'B', 'C')
<class 'tuple'>


In [2]:
import numpy as np

# 실습2 정수 n을 입력받아 n*n크기의 숫자 사각형 출력

n = 6
A = np.zeros((n,n))
for j in range(n):
    for i in range(n):
        A[j,i] = j*n+1
print(A)

[[ 1.  1.  1.  1.  1.  1.]
 [ 7.  7.  7.  7.  7.  7.]
 [13. 13. 13. 13. 13. 13.]
 [19. 19. 19. 19. 19. 19.]
 [25. 25. 25. 25. 25. 25.]
 [31. 31. 31. 31. 31. 31.]]


In [3]:
# 실습 3 실습 1에서 수행한 결과를 reshape를 이용해서 1차원 형태로 변환한다

print(A.reshape(-1,))


NameError: name 'A' is not defined

In [1]:
import numpy as np
from PIL import Image

# 이미지 파일 불러오기
image_path = 'joyul.jpeg'  # 이미지 파일 경로를 여기에 입력하세요
image = Image.open(image_path)
image_np = np.array(image)

# 차원 확장: (Height, Width, Channel) -> (Batch, Height, Width, Channel)
image_expanded = np.expand_dims(image_np, axis=0)

# 차원 변경: (Batch, Height, Width, Channel) -> (Batch, Channel, Width, Height)
image_transposed = np.transpose(image_expanded, (0, 3, 2, 1))

# 최종 결과의 shape 확인
print("Final transposed image shape:", image_transposed.shape)  # (Batch, Channel, Width, Height)


Final transposed image shape: (1, 3, 800, 533)


In [2]:
# 실습 4

import cv2
img = cv2.imread('./joyul.jpeg')
print(img.shape)
img_expend = np.expand_dims(img, 0)
print(img_expend.shape)
img_expend_T = img_expend.transpose((0, 3, 1, 2))
print(img_expend_T.shape)

(533, 800, 3)
(1, 533, 800, 3)
(1, 3, 533, 800)


In [3]:
# 실습 5

import cv2
import numpy as np

img = cv2.imread('lena.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1,]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)    ## --> 직접 구현해보기
cv2.imshow('edge', output)
cv2.waitKey(0)

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


[ WARN:0@4002.299] global loadsave.cpp:248 findDecoder imread_('lena.png'): can't open/read file: check file path/integrity


error: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/filter.dispatch.cpp:1528: error: (-215:Assertion failed) !_src.empty() in function 'filter2D'


In [3]:
# 실습 5 Answer

import cv2
import copy
import matplotlib.pyplot as plt
img = cv2.imread('./joyul.jpeg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
kernel = np.array([[1,1,1],[1,-8,1],[1,1,1]])
imgcpy = copy.deepcopy(img)
imgcpy2 = np.zeros( (imgcpy.shape[0], imgcpy.shape[1], imgcpy.shape[2]))

for h in range(2, img.shape[0]-1):
    for w in range(2, img.shape[1]-1):
        for c in range(1, img.shape[2]):
            img_tmp = np.dot(
                img[h-1:h-1+kernel.shape[0], w-1:w-1+kernel.shape[1], c], kernel)
            imgcpy2[h,w,c] = np.sum(img_tmp)

cv2.imshow("Edge", imgcpy2/255)
cv2.waitKey(1)

-1