# Homework1

In [2]:
A = ('A', 'B')
A + ('C',)

('A', 'B', 'C')

In [3]:
A = ('A', 'B')
Al = list(A)
Al.append('C')
A = tuple(Al)
print(A)
print(type(A))

('A', 'B', 'C')
<class 'tuple'>


# Homework2,3

In [5]:
import numpy as np

n = 6
A = np.zeros((n,n), dtype = int)
for j in range(n):
    for i in range(n):
        A[j,i] = n*j+i+1
print(A)
print(A.reshape(-1,))


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


# Homework4

In [21]:
import numpy as np
import cv2

img = cv2.imread('openCV/dog.png')
print(img.shape)
img_expend = np.expand_dims(img, 0)
print(img_expend.shape)
img_expend_T = img_expend.transpose((0, 3, 1, 2))
print(img_expend_T.shape)

[ WARN:0@311.397] global loadsave.cpp:248 findDecoder imread_('openCV/dog.png'): can't open/read file: check file path/integrity


AttributeError: 'NoneType' object has no attribute 'shape'

# Homework5

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import copy

In [ ]:
# convolution
img = cv2.imread('lena.png')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1]])
#print(img.shape[1])
imgcpy = copy.deepcopy(img)
imgcpy2 = np.zeros((imgcpy.shape[0], imgcpy.shape[1], imgcpy.shape[2]), dtype = int) 
#imgcpy2 = np.zeros((imgcpy.shape[0], imgcpy.shape[1]), dtype = int) 

plt.imshow(img/255)

In [ ]:
for h in range(2, img.shape[0]-1):
    for w in range(2, img.shape[1]-1):
        #img_tmp = np.dot(imgcpy[h-1:h-1+kernel.shape[0], w-1:w-1+kernel.shape[1]], kernel)
        #imgcpy2[h,w] = np.sum(img_tmp)
        for c in range(1, img.shape[2]):
            img_tmp = np.dot(img[h-1:h-1+kernel.shape[0], w-1:w-1+kernel.shape[1], c], kernel)
            imgcpy2[h,w,c] = np.sum(img_tmp)

#img3 = cv2.cvtColor(imgcpy2, cv2.COLOR_BGR2RGB)
plt.imshow(imgcpy2/255)