In [ ]:
#실습1
data1 = ('A','B')
data2 = ('C',)
data3 = data1 + data2

In [18]:
import numpy as np

n=6
A= np.zeros((n,n))
for j in range(n):
    for i in range(n):
        A[j,i] = j*n+i+1
print(A)
    

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36.]]


In [23]:
print(A.reshape(-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.]


In [32]:
import cv2

img =cv2.imread('img.png')
print(img.shape)
img_expend = np.expand_dims(img,0)
print(img_expend.shape)
img_expend_T = img_expend.transpose((0,3,1, 2))
print(img_expend_T.shape)


(275, 183, 3)
(1, 275, 183, 3)
(1, 3, 275, 183)


In [2]:
import cv2
import numpy as np

img= cv2.imread('img.png',cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1,1,1],[1,-8,1],[1,1,1]])
print(kernel)
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('edge',output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


In [1]:
import cv2 
import numpy as np

img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
print(kernel)


padded_img = np.pad(img, ((1, 1), (1, 1)), mode='constant')

output = np.zeros_like(img)

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        sum = 0
        for a in range(kernel.shape[0]):
            for b in range(kernel.shape[1]):
                sum += padded_img[i+a, j+b] * kernel[a, b]
        output[i, j] = np.clip(sum, 0, 255)

cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]
