## EDGE

In [10]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
import cv2
import numpy as np

img = cv2.imread('hanni_shortcut.jpg',cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1,1,1],[1,-8,1],[1,1,1]])
print(kernel)
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('edge',output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()


[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread

## IDENTIFY

In [2]:
kernel = np.array([[0,0,0],[0,1,0],[0,0,0]])
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('Identify',output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread

## Ridge 

In [3]:
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]])
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('Ridge',output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread

## Edge Detection

In [4]:
kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('Edge Detection',output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread

## Sharpen

In [5]:
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('Sharpen',output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread

## Box Blur

In [7]:
kernel = np.array([[1,1,1],[1,1,1],[1,1,1]])
kernel = kernel / 9
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('Box Blur',output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread

## Gaussian Blur 3x3

In [8]:
kernel = np.array([[1,2,1],[2,4,2],[1,2,1]])
kernel = kernel / 16
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('Gaussian Blur 3x3',output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread

## Gaussian Blur 5x5

In [9]:
kernel = np.array([[1,4,6,4,1],[4,16,24,16,4],[6,24,36,24,6],[4,16,24,16,4],[1,4,6,4,1]])
kernel = kernel / 256
output = cv2.filter2D(img,-1,kernel)
cv2.imshow('Gaussian Blur 5x5',output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread (0x14136f0).
Cannot move to target thread (0x12187a0)

QObject::moveToThread: Current thread (0x12187a0) is not the object's thread