In [1]:
# 실습1
import numpy as np

A = ('A', 'B')
C = A + ('C',)

print(C)
print(type(C))


('A', 'B', 'C')
<class 'tuple'>


In [2]:
# 실습2
n = 6
A = np.zeros((n,n))
for j in range(n):
    for i in range(n):
        A[j,i] = j*n+i
print(A)

num = 1
for i in range(6):
    for j in range(6):
        print(num, end=" ")
        num = num + 1
    print()


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
1 2 3 4 5 6 
7 8 9 10 11 12 
13 14 15 16 17 18 
19 20 21 22 23 24 
25 26 27 28 29 30 
31 32 33 34 35 36 


In [3]:
# 실습3
A = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
#print(A.reshape(-1,))

A_array = np.array(A)
A_1d = A_array.reshape(-1)
print(A_1d)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [4]:
# 실습4
import cv2
import numpy as np
# 이미지 파일 경로
image_path = "cat01_256.png"

# 이미지 읽기
image = cv2.imread(image_path)
print(image.shape)
expand_img = np.expand_dims(image, axis=0)
#expand_arr = np.expand_dims(image, 0)
print(expand_img.shape)

expand_img_T = expand_img.transpose((0,3,1,2))
print(expand_img_T.shape)


(256, 256, 3)
(1, 256, 256, 3)
(1, 3, 256, 256)


In [32]:
# 실습5 - 원소스
import cv2
import numpy as np

img = cv2.imread('cat01_256.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)

cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


In [ ]:
import cv2
import numpy as np

def filter2D(img, kernel):
    # 커널 크기
    k_height, k_width = kernel.shape
    
    # 패딩 크기 계산
    pad_height = k_height // 2
    pad_width = k_width // 2
    
    # 입력 이미지의 높이와 너비
    height, width = img.shape[:2]
    
    # 출력 이미지 크기 계산
    out_height = height - k_height + 2 * pad_height + 1
    out_width = width - k_width + 2 * pad_width + 1
    
    # 출력 이미지 초기화
    out_img = np.zeros((out_height, out_width), dtype=np.float32)
    
    # 패딩 추가
    padded_img = np.pad(img, ((pad_height, pad_height), (pad_width, pad_width)), mode='constant')
    
    # 컨볼루션 연산 수행
    for i in range(out_height):
        for j in range(out_width):
            temp = padded_img[i:i+k_height, j:j+k_width]
            out_img[i, j] = np.sum(temp * kernel)
 
    return out_img

img = cv2.imread('cat01_256.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1]])
print(kernel)
output = filter2D(img, kernel)
output2 = cv2.filter2D(img, -1, kernel)

cv2.imshow('edge', output)
cv2.imshow('edge2', output2)
cv2.waitKey(0)
cv2.destroyAllWindows()
