In [1]:
import cv2
import numpy as np

In [9]:
img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


In [12]:
img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, 0, 0],[0, 1, 0], [0, 0, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [13]:
img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0],[-1, 4, -1], [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]


In [16]:
img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[-1, -1, -1],[-1, 8, -1], [-1, -1, -1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[-1 -1 -1]
 [-1  8 -1]
 [-1 -1 -1]]


In [17]:
img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0],[-1, 5, -1], [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]


In [ ]:
img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/9, 1/9, 1/9],[1/9, 1/9, 1/9], [1/9, 1/9, 1/9]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/16, 2/16, 1/16],
                   [2/16, 4/16, 2/16], 
                   [1/16, 2/16, 1/16]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
img = cv2.imread('img.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/256, 4/256, 6/256, 4/256, 1/256],
                   [4/256, 16/256, 24/256, 16/256, 4/256], 
                   [6/256, 24/256, 36/256, 24/256, 6/256],
                   [4/256, 16/256, 24/256, 16/256, 4/256],
                   [1/256, 4/256, 6/256, 4/256, 1/256]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0.00390625 0.015625   0.0234375  0.015625   0.00390625]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.0234375  0.09375    0.140625   0.09375    0.0234375 ]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.00390625 0.015625   0.0234375  0.015625   0.00390625]]
