In [6]:
import tensorflow as tf
import numpy as np
import matplotlib.pylab as plt

## NoBatch

In [7]:
model_NoBatch = tf.keras.models.load_model('./mnist_NoBatch.h5')
mnist = tf.keras.datasets.mnist
(image_train, label_train), (image_test, label_test) = mnist.load_data()

image_train, image_test = image_train/255.0, image_test/255.0

num = 10
predict = model_NoBatch.predict(image_test[:num])
print(label_train[:num])
print(" * Prediction, ", np.argmax(predict, axis=1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
[5 0 4 1 9 2 1 3 1 4]
 * Prediction,  [1 1 1 1 1 1 1 1 1 1]


## Batch

In [8]:
model_Batch = tf.keras.models.load_model('./mnist_Batch.h5')
mnist = tf.keras.datasets.mnist
(image_train, label_train), (image_test, label_test) = mnist.load_data()

image_train, image_test = image_train/255.0, image_test/255.0

num = 10
predict = model_Batch.predict(image_test[:num])
print(label_train[:num])
print(" * Prediction, ", np.argmax(predict, axis=1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
[5 0 4 1 9 2 1 3 1 4]
 * Prediction,  [7 2 1 0 4 1 4 9 5 9]


## Relu

In [9]:
model_Relu = tf.keras.models.load_model('./mnist_Relu.h5')
mnist = tf.keras.datasets.mnist
(image_train, label_train), (image_test, label_test) = mnist.load_data()

image_train, image_test = image_train/255.0, image_test/255.0

num = 10
predict = model_Relu.predict(image_test[:num])
print(label_train[:num])
print(" * Prediction, ", np.argmax(predict, axis=1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
[5 0 4 1 9 2 1 3 1 4]
 * Prediction,  [7 2 1 0 4 1 4 9 5 9]
