In [1]:
import numpy as np
import cv2
import copy

A = ('A', 'B')
C = A + ('C', )
print(C)
print(type(C))

('A', 'B', 'C')
<class 'tuple'>


In [2]:
n = 4
A = np.zeros((n, n))

for j in range(n):
    for i in range(n):
        A[j, i] = j*n+i
print(A)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [3]:
print(A.reshape(-1,))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [4]:
image_path = "apple.jpg"
image = cv2.imread(image_path)

expanded_image = np.expand_dims(image, axis=0)

transposed_image = np.transpose(expanded_image, (0, 3, 1, 2))

print(image.shape)
print(expanded_image.shape)
print(transposed_image.shape)

(534, 532, 3)
(1, 534, 532, 3)
(1, 3, 534, 532)


In [5]:
img = cv2.imread("apple.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
kernel = np.array([[1,1,1],[1,-8,1],[1,1,1]])
print(kernel)

imgcpy = copy.deepcopy(img)
imgcpy2 = np.zeros((imgcpy.shape[0],imgcpy.shape[1],imgcpy.shape[2]))

for h in range(2, img.shape[0]-1):
    for w in range(2, img.shape[1]-1):
        for c in range(1, img.shape[2]):
            img_tmp = np.dot(
                img[h-1:h-1+kernel.shape[0], w-1:w-1+kernel.shape[1], c],
                kernel)
            imgcpy2[h,w,c] = np.sum(img_tmp)
        
# output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', imgcpy2/255)
cv2.waitKey(0)

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


113