In [2]:
# 실습1
x = ('A', 'B')
y = x + ('C', )
y

('A', 'B', 'C')

In [3]:
# 실습1
x_list = list(x)
x_list.append('C')
x_list = tuple(x_list)
x_list

('A', 'B', 'C')

In [2]:
# 실습2
import numpy as np
n = 6
square = np.zeros((n, n))
for i in range(n) :
    for j in range(n) :
        square[j,i] = j * n + i
square

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [3]:
# 실습3
print(square.reshape(-1,))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.]


In [4]:
# 실습4
import cv2
img = cv2.imread('loopy.png')
print(img.shape)
img_expand = np.expand_dims(img, 0)
print(img_expand.shape)
img_transpose = img_expand.transpose((0,3,1, 2))
print(img_transpose.shape)

(525, 393, 3)
(1, 525, 393, 3)
(1, 3, 525, 393)


In [32]:
img = cv2.imread('loopy.png')
kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


100

In [9]:
# 실습5
import copy
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
imgcpy = copy.deepcopy(img)
imgcpy2 = np.zeros((imgcpy.shape[0], imgcpy.shape[1], imgcpy.shape[2]))

for h in range(2, img.shape[0] - 1) :
    for w in range(2, img.shape[1] - 1) :
        for c in range(1, img.shape[2]) :
            img_tmp= np.dot(img[h-1:h-1+kernel.shape[0], w-1:w-1+kernel.shape[1],c],kernel)
            imgcpy2[h, w, c] = np.sum(img_tmp)

cv2.imshow('edge', imgcpy2/255)
cv2.waitKey(0)

100