## 실습1

In [3]:
a=("A", "B")
b=("C", )

a += b
print(a)
print(type(a))

('A', 'B', 'C')
<class 'tuple'>


## 실습2

In [5]:
import numpy as np

n=4
A=np.zeros((n,n))
for j in range(n):
    for i in range(n):
        A[j,i] = j*n+i
print(A)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


## 실습3

In [7]:
print(A.reshape(-1,))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
