In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


115

In [3]:
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('identity', output)
cv2.waitKey(0)

[[0 0 0]
 [0 1 0]
 [0 0 0]]


115

In [4]:
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0], [-1, 4, -1], [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('ridge', output)
cv2.waitKey(0)

[[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]


115

In [5]:
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge detection', output)
cv2.waitKey(0)

[[-1 -1 -1]
 [-1  8 -1]
 [-1 -1 -1]]


115

In [6]:
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('sharpen', output)
cv2.waitKey(0)

[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]


115

In [7]:
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/9, 1/9, 1/9], [1/9, 1/9, 1/9], [1/9, 1/9, 1/9]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('box blus', output)
cv2.waitKey(0)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


115

In [8]:
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/16, 1/8, 1/16], [1/8, 1/4, 1/8], [1/16, 1/8, 1/16]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('gaussian blur 3x3', output)
cv2.waitKey(0)

[[0.0625 0.125  0.0625]
 [0.125  0.25   0.125 ]
 [0.0625 0.125  0.0625]]


115

In [9]:
img = cv2.imread('loopy.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/256, 4/256, 6/256, 4/256, 1/256], [4/256, 16/256, 24/256, 16/256, 4/256], [6/256, 24/256, 36/256, 24/256, 6/256], [4/256, 16/256, 24/256, 16/256, 4/256], [1/256, 4/256, 6/256, 4/256, 1/256]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('gaussian blur 5x5', output)
cv2.waitKey(0)

[[0.00390625 0.015625   0.0234375  0.015625   0.00390625]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.0234375  0.09375    0.140625   0.09375    0.0234375 ]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.00390625 0.015625   0.0234375  0.015625   0.00390625]]


115