In [8]:
import cv2
import numpy as np
img = cv2.imread('spongebob.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


In [10]:
img = cv2.imread('spongebob.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, 0, 0],[0, 1, 0], [0, 0, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [19]:
img = cv2.imread('spongebob.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0],[-1, 4, -1], [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

[[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]


In [18]:
img = cv2.imread('spongebob.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[-1, -1, -1],[-1, 8, -1], [-1, -1, -1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

[[-1 -1 -1]
 [-1  8 -1]
 [-1 -1 -1]]


In [13]:
img = cv2.imread('spongebob.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0],[-1, 5, -1], [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]


In [14]:
img = cv2.imread('spongebob.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/9, 1/9, 1/9],[1/9, 1/9, 1/9], [1/9, 1/9, 1/9]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [15]:
img = cv2.imread('spongebob.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/16, 1/8, 1/16],[1/8, 1/4, 1/8], [1/16, 1/8, 1/16]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

[[0.0625 0.125  0.0625]
 [0.125  0.25   0.125 ]
 [0.0625 0.125  0.0625]]


In [17]:
img = cv2.imread('spongebob.png', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/256, 4/256, 6/256, 4/256, 1/256],[4/256, 16/256, 24/256, 16/256, 4/256], [6/256, 24/256, 36/256, 24/256, 6/256],[4/256, 16/256, 24/256, 16/256, 4/256],[1/256, 4/256, 6/256, 4/256, 1/256]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
key = cv2.waitKey(0)
if key & 0xFF == ord('q'):
    cv2.destroyAllWindows()

[[0.00390625 0.015625   0.0234375  0.015625   0.00390625]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.0234375  0.09375    0.140625   0.09375    0.0234375 ]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.00390625 0.015625   0.0234375  0.015625   0.00390625]]
