In [1]:
import cv2
import numpy as np

img = cv2.imread('bw_image.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1,1,1],[1,-8,1],[1,1,1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)


[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


113

In [1]:
# identity
import cv2
import numpy as np

img = cv2.imread('bw_image.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0,0,0],[0,1,0],[0,0,0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)


[[0 0 0]
 [0 1 0]
 [0 0 0]]


113

In [1]:
# Ridge or edge detection
import cv2
import numpy as np

img = cv2.imread('bw_image.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)


[[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]


113

In [1]:
# Ridge or edge detection
import cv2
import numpy as np

img = cv2.imread('bw_image.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

[[-1 -1 -1]
 [-1  8 -1]
 [-1 -1 -1]]


113

In [1]:
#sharpen
import cv2
import numpy as np

img = cv2.imread('bw_image.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]


113

In [ ]:
#box blur
import cv2
import numpy as np

img = cv2.imread('bw_image.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(kernel)
output = cv2.filter2D(img, -1, (1/9)*kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

In [ ]:
#caussian blur(3x3)
import cv2
import numpy as np

img = cv2.imread('bw_image.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1,8,1],[2,4,2],[1,2,1]])
print(kernel)
output = cv2.filter2D(img, -1, (1/16)*kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

In [ ]:
#caussian blur(5x5)
import cv2
import numpy as np

img = cv2.imread('bw_image.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1,4,6,4,1],[4,16,24,16,4],[6,24,36,24,6],[4,16,24,16,4],[1,4,6,4,1]])
print(kernel)
output = cv2.filter2D(img, -1, (1/256)*kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)