In [3]:
import cv2
import numpy as np

In [8]:
#Convolution
#edge
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1],[1, -8, 1], [1, 1, 1]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[ 1  1  1]
 [ 1 -8  1]
 [ 1  1  1]]


In [5]:
#Identity
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, 0, 0],
                   [0, 1, 0], 
                   [0, 0, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('Identity', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [9]:
#Sharpen
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[0, -1, 0],
                   [-1, 5, -1], 
                   [0, -1, 0]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('Sharpen', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]


In [10]:
#Box blur
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/9, 1/9, 1/9],
                   [1/9, 1/9, 1/9], 
                   [1/9, 1/9, 1/9]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('Box blur', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [11]:
#Gaussian blur 3x3
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/16, 2/16, 1/16],
                   [2/16, 4/16, 2/16], 
                   [1/16, 2/16, 1/16]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('Gaussian blur 3x3', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[0.0625 0.125  0.0625]
 [0.125  0.25   0.125 ]
 [0.0625 0.125  0.0625]]


In [12]:
#Gaussian blur 5x5
img = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1/256,  4/256,   6/256 ,  4/256, 1/256],
                   [4/256, 16/256, 246/256 , 16/256, 4/256], 
                   [6/256, 24/256,  36/256 , 24/256, 6/256],
                   [4/256, 16/256,  24/256 , 16/256, 4/256],
                   [1/256,  4/256,   6/256 ,  4/256, 1/256]])
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('Gaussian blur 5x5', output)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[0.00390625 0.015625   0.0234375  0.015625   0.00390625]
 [0.015625   0.0625     0.9609375  0.0625     0.015625  ]
 [0.0234375  0.09375    0.140625   0.09375    0.0234375 ]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.00390625 0.015625   0.0234375  0.015625   0.00390625]]
