In [1]:
import cv2
import numpy as np


img_path = "my_image.png"
img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
kernel = np.array([[-1, -1, -1], [0, 0, 0], [1, 1, 1]])
k_sharpen = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
k_blur = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]]) / 16
print(kernel)
output = cv2.filter2D(img, -1, kernel)
cv2.imshow('edge', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]


In [5]:
import numpy as np
np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]])/16

array([[0.0625, 0.125 , 0.0625],
       [0.125 , 0.25  , 0.125 ],
       [0.0625, 0.125 , 0.0625]])